---
title: "Lab4"
author: "Group5"
date: "March 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)
names(av)
av
```
1.

```{r}
allinone <- av %>% gather(Time, Outcome, starts_with("Death")) 
allinone <- allinone %>% mutate(Event= gsub("(.*)[1-5]", "\\1", Time),Time=parse_number(Time))
allinone %>% filter(Event == "Death") %>% count(Outcome)
allinone <- av %>% gather(Time, Outcome, starts_with("Return"))

```
```{r}
allinone <- av %>% gather(Time, Outcome, starts_with("Return"))
allinone <- allinone %>% mutate(Event= gsub("(.*)[1-5]", "\\1", Time),Time=parse_number(Time))
allinone %>% filter(Event == "Return") %>% count(Outcome)
```

2.

Based on the article, it says that they counted a total of 89 deaths and out of those, there were a total of 57 comebacks. This statement can be confirmed by our data. Above, within the total number of deaths, there were 89 and out of those came a total of 57 returns with the yes columns having an 89 in terms of deaths and 57 returns that had a yes, as well.
